name: '📋 Pull Request'
description: 코드 변경 PR 템플릿
title: '[Feat] 간결한 제목을 작성하세요'

body:
  - type: textarea
    id: changes
    attributes:
      label: 📋 변경 사항
      description: 이 PR에서 무엇을 변경했는지 간략히 설명
      placeholder: |
        - 로그인 훅 리팩터링
        - 프로필 편집 모달 추가
    validations:
      required: true

  - type: textarea
    id: issues
    attributes:
      label: 🔗 관련 이슈
      description: |
        `Closes #123` 형식으로 입력하면 PR 머지 시 자동으로 이슈가 닫힙니다.
      placeholder: |
        - Closes #45
        - Related to #67
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 스크린샷 (UI 변경)
      description: UI 변경이 있는 경우 추가
      placeholder: |
        Before | After
        --- | ---
        ![before](url) | ![after](url)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 체크리스트
      options:
        - label: 코드가 스타일 가이드를 따릅니다
        - label: 자체 코드 리뷰를 완료했습니다
        - label: 복잡/핵심 로직에 주석을 추가했습니다
        - label: 관심사 분리를 확인했습니다
        - label: 잠재적 사이드이펙트를 점검했습니다
        - label: Vercel Preview 로 테스트를 완료했습니다

  - type: textarea
    id: tests
    attributes:
      label: 🧪 테스트
      description: 변경 사항을 어떻게 검증했는지
      placeholder: |
        - [x] 로그인 플로우 수동 테스트
        - [x] AuthSlice 단위 테스트 통과
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 📝 추가 노트
      description: 리뷰어가 알아두면 좋은 정보
      placeholder: |
        - API 응답 타입 변경 → mobile 쪽 작업 필요
    validations:
      required: false
