#!/usr/bin/env sh

echo "🐕 Husky Git Hooks 가이드"
echo "=========================="
echo ""
echo "📋 설정된 Hooks:"
echo ""
echo "🔍 pre-commit:"
echo "  - ESLint 자동 수정 (변경된 .ts, .tsx 파일)"
echo "  - Prettier 포맷팅 (변경된 .json, .md, .css 파일)"
echo ""
echo "📝 commit-msg:"
echo "  - 컨벤셔널 커밋 형식 검증"
echo "  - 허용 타입: feat, fix, docs, style, refactor, test, chore, perf, ci, build"
echo "  - 예시: feat: 사용자 로그인 기능 추가"
echo ""
echo "🚀 pre-push:"
echo "  - 브랜치명 컨벤션 검증"
echo "  - TypeScript 타입 체크"
echo "  - 단위 테스트 실행"
echo ""
echo "🔄 post-merge:"
echo "  - 의존성 변경 감지 시 자동 설치"
echo "  - Turbo 캐시 정리"
echo ""
echo "🌿 post-checkout:"
echo "  - 브랜치 전환 시 정보 표시"
echo "  - 의존성 변경 알림"
echo "  - 미완료 작업 알림"
echo ""
echo "↩️  pre-rebase:"
echo "  - Protected 브랜치 리베이스 방지"
echo "  - 미커밋 변경사항 확인"
echo ""
echo "🛠️  유용한 명령어:"
echo "  pnpm commitlint          - 마지막 커밋 메시지 검증"
echo "  git commit --no-verify   - 훅 건너뛰기 (비상시만)"
echo "  git push --no-verify     - 푸시 훅 건너뛰기 (비상시만)"
echo ""