name: CI

on:
  push:
    branches: [dev] # 🚩 기본 브랜치
  pull_request:
    branches: [dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # pnpm + Node
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # Turbo cache
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: turbo-${{ runner.os }}-

      # Lint + Test (typecheck 제거)
      - name: Lint & Test
        run: pnpm turbo run lint test --cache-dir=".turbo"
