# .github/workflows/pr-branch-guard.yml
name: PR branch guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Validate base/head
        env:
          BASE: ${{ github.event.pull_request.base.ref }}
          HEAD: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Base=$BASE  Head=$HEAD"

          # ──────────────── 1) main 보호 ────────────────
          #  - 오직 fix/* 만 main 으로 PR 가능
          if [[ "$BASE" == "main" && ! "$HEAD" =~ ^fix/.+ ]]; then
            echo "❌  main 으로는 fix/* PR만 허용됩니다."
            exit 1
          fi

          # ──────────────── 2) dev 보호 ────────────────
          #  - feat/*, fix/* 만 dev 로 PR 가능
          if [[ "$BASE" == "dev" && ! "$HEAD" =~ ^(feat|fix)/.+ ]]; then
            echo "❌  dev 으로는 feat/* 또는 fix/* PR만 허용됩니다."
            exit 1
          fi
