name: Sync PR → Fork for Preview

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, synchronize]

jobs:
  sync_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Push PR branch to personal fork
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: '.' # monorepo 전체
          destination-github-username: DreamPaste
          destination-repository-name: SOSO-Front-End
          target-branch: ${{ github.event.pull_request.head.ref }}
          create-target-branch-if-needed: true
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: 'ci: sync PR #${{ github.event.pull_request.number }} @ ${{ github.sha }}'
